package com.bobo.easy;

/**
 * Created by evildoerDb on 2018/8/8 17:50
 *
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 *
 *
 * 389
 */
public class FindTheDifference {

    /**
     * 经典装桶法
     * @param s
     * @param t
     * @return
     */
    public static char findTheDifference(String s, String t) {
        int[] arr = new int[26];
        for (int i = 0; i < t.length(); i++){
            arr[t.charAt(i) - 'a']++;
        }
        for (int i = 0; i < s.length(); i++){
            arr[s.charAt(i) - 'a']--;
        }
        for (int i = 0 ; i < arr.length; i++){
            if (arr[i] > 0){
                return (char) (i + 97 );
            }
        }
        return ' ';
    }


    public static void main(String[] args) {
        System.out.println(findTheDifference("abcd","abcde"));
    }
}
